In [7]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA


data = {
    'Height': [150,160,170,180,190],
    'Weight': [50,60,65,75,85],
    'Age': [20,25,30,35,40]
}

df = pd.DataFrame(data)

print("Original Data")
print(df)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)


pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

print("\nReduced Data")
print(X_pca)

print("\nExplained Variance")
print(pca.explained_variance_ratio_)

print("\nEigenvalues")
print(pca.explained_variance_)


print("\nEigenvectors")
print(pca.components_)

Original Data
   Height  Weight  Age
0     150      50   20
1     160      60   25
2     170      65   30
3     180      75   35
4     190      85   40

Reduced Data
[[-2.44528861  0.00395897]
 [-1.15105396  0.10339833]
 [-0.09545379 -0.13522512]
 [ 1.19878086 -0.03578576]
 [ 2.4930155   0.0636536 ]]

Explained Variance
[0.99771166 0.00228834]

Eigenvalues
[3.74141872 0.00858128]

Eigenvectors
[[ 0.57768199  0.57668626  0.57768199]
 [-0.40777877  0.8169657  -0.40777877]]


In [2]:
import numpy as np

marks = [48, 49, 50, 51, 52]


mean = np.mean(marks)


sd = np.std(marks)

print("Marks:", marks)
print("Mean:", mean)
print("Standard Deviation:", sd)

Marks: [48, 49, 50, 51, 52]
Mean: 50.0
Standard Deviation: 1.4142135623730951


In [5]:
import pandas as pd
from sklearn.linear_model import LinearRegression

data = {
    'Hours': [1, 2, 3, 4, 5],
    'Marks': [35, 45, 50, 60, 70]
}

df = pd.DataFrame(data)

print("Dataset")
print(df)


x = df[['Hours']]


y = df['Marks']


model = LinearRegression()


model.fit(x, y)
new_data = pd.DataFrame({
    'Hours': [6]
})

prediction = model.predict(new_data)



print("\nPredicted Marks for 6 Hours:", prediction[0])


print("\nSlope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

Dataset
   Hours  Marks
0      1     35
1      2     45
2      3     50
3      4     60
4      5     70

Predicted Marks for 6 Hours: 77.5

Slope (Coefficient): 8.500000000000002
Intercept: 26.499999999999993


In [6]:
import pandas as pd
from sklearn.linear_model import LinearRegression


data = {
    'Hours': [1, 2, 3, 4, 5],
    'Attendance': [60, 70, 80, 90, 95],
    'Previous_Marks': [40, 45, 55, 60, 70],
    'Final_Marks': [45, 52, 60, 68, 78]
}

df = pd.DataFrame(data)

print("Dataset")
print(df)


X = df[['Hours', 'Attendance', 'Previous_Marks']]


y = df['Final_Marks']


model = LinearRegression()


model.fit(X, y)


new_student = pd.DataFrame({
    'Hours': [6],
    'Attendance': [96],
    'Previous_Marks': [75]
})

prediction = model.predict(new_student)

print("\nPredicted Final Marks:", prediction[0])

print("\nCoefficients:")
for feature, coef in zip(X.columns, model.coef_):
    print(f"{feature}: {coef}")

print("\nIntercept:", model.intercept_)

Dataset
   Hours  Attendance  Previous_Marks  Final_Marks
0      1          60              40           45
1      2          70              45           52
2      3          80              55           60
3      4          90              60           68
4      5          95              70           78

Predicted Final Marks: 89.55000000000001

Coefficients:
Hours: 11.500000000000014
Attendance: -0.44999999999999996
Previous_Marks: 0.09999999999999855

Intercept: 56.250000000000036


In [8]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures


data = {
    'Years': [1, 2, 3, 4, 5],
    'Salary': [30000, 35000, 50000, 80000, 120000]
}

df = pd.DataFrame(data)

print("Dataset")
print(df)


X = df[['Years']]


y = df['Salary']

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)


model = LinearRegression()


model.fit(X_poly, y)


new_data = pd.DataFrame({
    'Years': [6]
})

new_data_poly = poly.transform(new_data)

prediction = model.predict(new_data_poly)

print("\nPredicted Salary:", prediction[0])

print("\nCoefficients:", model.coef_)
print("Intercept:", model.intercept_)

Dataset
   Years  Salary
0      1   30000
1      2   35000
2      3   50000
3      4   80000
4      5  120000

Predicted Salary: 173000.00000000006

Coefficients: [     0.         -13928.57142857   6071.42857143]
Intercept: 37999.99999999994
